/*
 * Copyright (C) 2001-2006 University Bayreuth, BayCEER, Dept. of Mycology 
 * 
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License 
 * along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */
/*
 * NaviKeyApplet.java
 *
 * Created on 7. April 2004, 15:11
 */

package net.metadiversity.diversity.navikey.ui;

/**
 *
 * @author Dieter Neubacher
 */
public class NaviKeyApplet extends javax.swing.JApplet
{
    /**
     * Comment for <code>serialVersionUID</code>
     */
    private static final long serialVersionUID = 3762811610460401970L;
    NaviKey navikey = null;
    
    /** Initializes the applet NaviKeyApplet */
    public void init()
    {
        System.out.println( "NaviKey" );
        navikey = new NaviKey( getContentPane(), getParameter( "configfile" ), getCodeBase() );
        System.out.print( "NaviKey init()" );       
        navikey.init();
        System.out.println( " ... finish" );       
        initComponents();
        
        java.applet.AppletContext appletContext = getAppletContext();
        
        navikey.setAppletContext( appletContext );
    }
    
    @Override
    public void stop() 
    {
        navikey = null;
    }

    @Override
    public void destroy() 
    {
        navikey = null;
    }
    
    
    
    /** This method is called from within the init() method to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
